
SAC_SETTING:
  LOG_INTERVAL: 1
  VERBOSE: 1
  LEARNING_RATE: 3e-4
  ENT_COEF: 'auto_0.1'
  TRAIN_FREQ: 1
  BATCH_SIZE: 64
  GRADIENT_STEPS: 600
  LEARNING_STARTS: 300
  BUFFER_SIZE: 30000
  VARIANTS_SIZE: 32
  IMAGE_CHANNELS: 3
  GAMMA: 0.99
  TAU: 0.02
  USER_SDE_AT_WARMUP: true
  USER_SDE: true
  SDE_SAMPLE_FREQ: 64



  #HyperParameter for Reward
REWARD_SETTING:
  REWARD_CRASH: -10
  CRASH_REWARD_WEIGHT: 5
  THROTTLE_REWARD_WEIGHT: 0.1

#AGENT_SETTING:
#  # Agent settings
#  N_COMMAND_HISTORY: 10
#  MIN_STEERING: -1.0
#  MAX_STEERING: 1.0
#  MIN_THROTTLE: 0.3
#  MAX_THROTTLE: 0.5
#  MAX_STEERING_DIFF: 0.15

#s#JetBot Reference
#AGENT_SETTING:
#  N_COMMAND_HISTORY: 10
#  MIN_STEERING: -0.5
#  MAX_STEERING: 0.5
#  MIN_THROTTLE: 0.3
#  MAX_THROTTLE: 0.5
#  MAX_STEERING_DIFF: 0.05

AGENT_SETTING:
  # Agent settings
  N_COMMAND_HISTORY: 20
  MIN_STEERING: -1.0
  MAX_STEERING: 1.0
  MIN_THROTTLE: 0.4 # 0.4
  MAX_THROTTLE: 0.7 # 0.9
  MAX_STEERING_DIFF: 0.9 #0.35

JETRACER_SETTING:
  STEERING_CHANNEL: 0
  THROTTLE_CHANNEL: 1
  STEERING_GAIN: -0.65
  THROTTLE_GAIN: -0.8
